#!/bin/zsh

mkdir -p output
line=""
out="tasklist.txt"
rm $out
counter=0
#h=1.4
#for nref in 1 2 3; do
for optre in 500 1000; do
  for nref in 1 2; do
    #for order in 1 2; do
    for order in 2; do
      for problem in "pipe" "obstacle"; do
        if [ $problem = "pipe" ]; then
          h=0.25
        else
          h=1.4
        fi
        #for disc in "sv" "pkp0"; do
        for disc in "pkp0"; do
          #for solver in "lu" "almg"; do
          for solver in "almg"; do
            for cr in 0.5 1 2 4; do
              for stab in "supg" "burman" "none"; do
                declare -a stabws
                if [ $stab = "supg" ]; then
                  stabws=(0.125 0.25 0.5 1.0)
                elif [ $stab = "burman" ]; then
                  stabws=("2e-3", "5e-3", "1e-2")
                else
                  stabws=( 0 )
                fi
                for stabw in ${stabws[@]}; do
                  if [ $disc = "sv" ]  && [ $solver = "almg" ] && [ $order = 2 ]; then
                    continue
                  fi
                  if [ $disc = "sv" ]  && [ $stab = "supg" ]; then
                    continue
                  fi

                  if [ $disc = "sv" ]; then
                    mh="bary"
                  else
                    mh="uniform"
                  fi
                  if [ $solver = "almg" ]; then
                    gamma=1e4
                  else
                    gamma=0
                  fi
                  smooth="--smooth"
                  tikhonov=1e-3
                  restr="--restriction"
                  label=$problem-$disc-nref-$nref-$solver-$mh$restr-stab-$stab-stabw-$stabw-gamma-$gamma-optre-$optre-order-$order-tikhonov-$tikhonov-cr-$cr$smooth
                  line="mpiexec -n 1 python3 pipeopt.py --solver-type $solver --patch star --discretisation $disc --mh $mh --k 2 --stabilisation-type $stab --stabilisation-weight $stabw --nref $nref --gamma $gamma $restr --order $order --time --problem $problem --opt-re $optre --label $label --element-size $h --tikhonov $tikhonov --cr $cr $smooth 2>&1 | tee output/$label.log"
                  delay=$((($counter%4)*5))
                  counter=$(($counter+1))
                  echo $line
                  echo "sleep ${delay}s; $line" >> $out
                done
              done
            done
          done
        done
      done
    done
  done
done
